version: '3'

services:
  webserver:
    image: nginx:1.23.4-alpine
    ports:
      - 3011:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./_site:/usr/share/nginx/html:ro
